[package]
name = "rust_app"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = false
codegen-units = 1

[dependencies]

#i_overlay = { path = "../../iOverlay", default-features = true }
#i_overlay = { path = "../../iOverlay", default-features = false }
i_overlay = "~3.3.2"