pub(crate) mod test_0_checkerboard;
pub(crate) mod test_1_not_overlap;
pub(crate) mod test_2_lines_net;
pub(crate) mod test_3_spiral;
pub(crate) mod test_4_windows;
pub(crate) mod test_5_nested_squares;
pub(crate) mod test_6_corrosion;
pub(crate) mod test_7_concentric;
pub(crate) mod test_8_wind_mill;
mod util;